### ISSUE TITLE
Restore packages in VSTS Build

### ISSUE THREAD

**Issue by MichaelWhiteCodingForFun** [touchifyapp/vsts-bower#2]
So i have a build definition on my team services project

My source code in the repo does not include the packages loaded via bower however I do have a bower.json file in the solution.

I want my bower task in the build to load my bower packages into the project and then to be included in the artifact drop output

My build does run the bower task but I dont see the output packages in the destination folder

Any help would be great

**Comment by SomaticIT** [comment]
Hi, sorry for my late answer.

Make there is not a configuration which excludes your `bower_components` from the destination folder.
The `vsts-task` is correctly installing your components, you can make sure by executing a command like `IF EXIST dest\bower_components ( echo OK ) ELSE ( echo NOK )`.

Thanks.
