### ISSUE TITLE
Bower install for multiple sub-projects

### ISSUE THREAD

**Issue by SeanSobeySage** [touchifyapp/vsts-bower#3]
Is there a way to run this task for multiple projects within a folder? Possibly with blob pattern/wildcards? For example we specify a root folder and all sub folders matching a pattern we run the bower command.

**Comment by SomaticIT** [comment]
As of now, the module can't be used on multiple projects.
But you can configure a single task per project. VSTS allows you to have multiple instances of the same task.

**Comment by SeanSobeySage** [comment]
Thanks for your reply, would you consider a pull request for that feature? Or possibly just limited to comma-separated paths?

**Comment by SomaticIT** [comment]
Of course :)
I'm more in favor of blob pattern instead of comma-separated paths.
